### ISSUE TITLE
Разделы на странице people всего в две колонки

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/platform#1000]
## Проблема

Разделы на странице участников отображаются на экранах > 1440px всего в колонки. А поместиться могут все 4!

### Как сейчас

![В 2 колонки](https://user-images.githubusercontent.com/91747573/195571976-c05fd9a8-9cba-4af0-a783-33f1074bd30b.png)

### Как вижу это я

![В 4 колонки](https://user-images.githubusercontent.com/91747573/195572155-8e0f2f42-f100-43f1-a9f7-d83267e7024a.png)

### Как я это сделал

<details>
  <summary>Моё решение</summary>

  Вот тут добавить ещё `articles`:

  https://github.com/doka-guide/platform/blob/23bf734eddd056203efd1185219525fd8408f0ba/src/styles/blocks/person-page.css#L124-L135

  ```css
  @media (min-width: 1440px) {
    .person-page {
      --sidebar-size-end: 1fr;
    }

    .person-page__main {
      grid-template-areas:
        'avatar header   .'
        'meta   articles articles'
        '.      footer   footer';
    }
  }
  ```

  А вот тут `max-width` увеличить хотя бы до `1440px`:

  https://github.com/doka-guide/platform/blob/23bf734eddd056203efd1185219525fd8408f0ba/src/styles/blocks/person-page.css#L59-L66

</details>
