### ISSUE TITLE
Сломаный размер шрифта для `<code>` в заголовках на главной

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/platform#1037]
## Проблема

Сейчас размер шрифта `<code>` в карточках статей на главной слишком маленький.

Как сейчас (36px)/как должно быть (42px):

| ![изображение](https://user-images.githubusercontent.com/91747573/200580381-5d154d02-ebf7-4ce4-9d55-576de56ec676.png) | ![изображение](https://user-images.githubusercontent.com/91747573/200580755-76a99aab-761f-4633-815b-d802aac4012d.png) |
|-|-|

## Причины

```css
.featured-article__code {
    font-size: var(--font-size, var(--font-size-m));
}
```

`--font-size` наследуется от:

```css
.featured-article__title {
    --font-size: var(--font-size-xl);
}
```

Но девтулзы говорят, что `--font-size-xl is not defined`.
