### ISSUE TITLE
Красиво задать отступы для списка разделов в хедере

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1296]
## Проблема

Изящно задать padding-и справа/слева у списка с разделами в дропдауне. Сейчас всё печально.

```css
@media (width >= 1024px) {
  .nav-list {
    --block-padding: 6px;
    --gap: 6px;
    padding-top: 0;
    padding-bottom: var(--list-padding-max);
    padding-right: var(--list-padding-max);
    padding-left: calc(37*var(--gap)); <------ 👀
    gap: 6px;
    line-height: inherit;
  }
}

@media (width >= 1366px) {
  .nav-list {
    padding-left: calc(38*var(--gap));  <------ 👀
  }
}

@media (width >= 1680px) {
  .nav-list {
    padding-left: calc(45*var(--gap));  <------ 👀
  }
}
```

Контекст описан [в комментарии к другому пиару](https://github.com/doka-guide/platform/pull/1191#issuecomment-2263818624).
