### ISSUE TITLE
Изящно рассчитать ширину skip link

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1297]
## Проблема

Пересчитать ширину скиплинка, т. к. она пока задана «в лоб»:

```css
skip-link {
  position: absolute;
  overflow: hidden;
  top: auto;
  left: -10000px;
  width: 1px;
  height: 1px;
  padding: 16px 52px; <------ 👀
  background-color: var(--color-background);
  z-index: 4;
}

.skip-link:focus-visible {
  top: 0;
  left: 0;
  width: auto;
  height: auto;
}

@media (width >= 1024px) {
  .skip-link {
    padding: 23px 56px; <------ 👀
  }
}

@media (width >= 1680px) {
  .skip-link {
    padding: 26px 62px; <------ 👀
  }
}
```
