### ISSUE TITLE
Появилась горизонтальная прокрутка на странице поиска

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/platform#939]
Firefox, Safari, Chrome, одинаково. Появляется только при непустых результатах. Вызывается вот этой конструкцией

```css
@media (min-width: 1024px) {
  .search__output:not(:empty) > .search-result-list {
    width: 809px;
  }
}
```

Вместо этого нам бы лучше поменять место `search-page__main` в гриде. Что-то вроде:

```css
.search-page__main {
  grid-column: 2 / -1;
}
```

Но это скоростной анализ и решение.
